version: '3.6'

services:
  alpine-apache2-reverse-proxy:
    image: hackinglab/alpine-apache2-reverse-proxy:latest
    environment:
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
      - "HL_ROOT_PASSWORD=dQ0edEdD6dWZMJj"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/proxy-html.conf:/etc/apache2/conf-frontend.d/proxy-html.conf
